name: Create and publish a docker images

on:
  push:
    branches:
      - 'main'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  CUDA_VERSION: 11.7.0
  CUDNN_VERSION: 8
  UBUNTU_VERSION: 22.04
  
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v2
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      # - name: Build and push gpu image
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: ./docker
      #     push: true
      #     tags: ${{ steps.meta.outputs.tags }},${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-gpu:latest
      #     labels: ${{ steps.meta.outputs.labels }}
      #     build-args: |
      #       BASE_IMAGE=nvidia/cuda:${{ env.CUDA_VERSION }}-cudnn${{ env.CUDNN_VERSION }}-devel-ubuntu${{ env.UBUNTU_VERSION }} 
      
      - name: Build and push base image
        uses: docker/build-push-action@v3
        with:
          context: ./base
          push: true
          tags: ${{ steps.meta.outputs.tags }},${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/base:latest
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BASE_IMAGE=ubuntu:${{ env.UBUNTU_VERSION }} 

      - name: Build and push cpu image
        uses: docker/build-push-action@v3
        with:
          context: ./workspace
          push: true
          tags: ${{ steps.meta.outputs.tags }},${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/cpu:latest
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BASE_IMAGE=ubuntu:${{ env.UBUNTU_VERSION }} 